version: '3'
services:
  gcc-clang-sample:
    image: 'gcc:9.2'
    volumes:
      - ./clang:/src/clang
    working_dir: /src/clang
    command: ./build.sh
  gcc-cpp-sample:
    image: 'gcc:9.2'
    volumes:
      - ./cpp:/src/cpp
    working_dir: /src/cpp
    command: ./build.sh
